# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: ejecutando echo

on:
  push:
    branches: [ "main" ]
  pull_request : 
    branches:  ["main"]
    
jobs:
  jhonatan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
       
      - uses: actions/setup-node@v4
        with:
          node-version: 20.14.0
          check-latest: false
          cache: 'npm'
      - run: npm install  

      - name: 'verificar'
        run: echo "hello"

      - name: 'View Files'
        run: ls -la
      
      - name: 'creation of build to deploy'
        run: npm run build
      
  

