# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: ejecutando echo

on:
  push:
    branches: [ "main" ]
    
jobs:
  jhonatan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: 'verificar'
        run: echo "hello"

      - name: 'View Files'
        run: ls
  

